# Generated by Django 3.2.15 on 2022-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('personapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
