# Generated by Django 3.2.15 on 2022-08-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('personapp', '0003_biodata_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='district',
            new_name='idukki',
        ),
        migrations.AddField(
            model_name='biodata',
            name='kannur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='kollam',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='palakkad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='trissur',
            field=models.BooleanField(default=True),
        ),
    ]
