# Generated by Django 3.2.15 on 2022-08-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0004_auto_20220825_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_account', models.TextField(max_length=20)),
                ('current_account', models.TextField(max_length=20)),
                ('NRI_account', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='biodata',
            name='age',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AddField(
            model_name='biodata',
            name='account',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='personapp.account'),
        ),
    ]
