# Generated by Django 3.2.15 on 2022-08-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0006_auto_20220826_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='meterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=20)),
                ('checkbook', models.BooleanField()),
                ('DebitCard', models.BooleanField()),
                ('crediCard', models.BooleanField()),
                ('passbook', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='idukki',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='kannur',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='kollam',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='palakkad',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='trissur',
        ),
    ]
