# Generated by Django 3.2.15 on 2022-08-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0007_auto_20220826_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbook', models.BooleanField()),
                ('DebitCard', models.BooleanField()),
                ('crediCard', models.BooleanField()),
                ('passbook', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='meterials',
        ),
        migrations.AddField(
            model_name='biodata',
            name='bank',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='personapp.bank'),
        ),
    ]
