# Generated by Django 3.2.15 on 2022-08-26 07:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('personapp', '0008_auto_20220826_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank',
            new_name='meterials',
        ),
    ]
