# Generated by Django 3.2.15 on 2022-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('personapp', '0009_rename_bank_meterials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meterials',
            new_name='bank',
        ),
    ]
