# Generated by Django 3.2.15 on 2022-08-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('personapp', '0015_book_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bio',
        ),
        migrations.AddField(
            model_name='biodata',
            name='book',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='personapp.book'),
        ),
    ]
