# Generated by Django 3.2.15 on 2022-08-27 17:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0017_alter_biodata_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='book',
        ),
        migrations.AddField(
            model_name='biodata',
            name='meterial',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BANK PASS BOOK', 'BANK PASS BOOK'), ('CREDIT CARD', 'CREDIT CARD'), ('DEBIT CARD', 'DEBIT CARD'), ('CHECKBOOK', 'CHECKBOOK')], default='BANK PASS BOOK', max_length=100),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
