# Generated by Django 3.2.15 on 2022-08-27 17:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0018_auto_20220827_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='type',
            field=models.CharField(choices=[('SAVINGS ACCOUNT', 'SAVINGS ACCOUNT'), ('CURRENT ACCOUNT', 'CURRENT ACCOUNT'), ('NRI ACCOUNT', 'NRI ACCOUNT')], default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='meterial',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BANK PASS BOOK', 'BANK PASS BOOK'), ('CREDIT CARD', 'CREDIT CARD'), ('DEBIT CARD', 'DEBIT CARD'), ('CHECKBOOK', 'CHECKBOOK')], default=False, max_length=100),
        ),
    ]
