# Generated by Django 3.2.15 on 2022-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0021_rename_biodata_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='meterial',
            new_name='meterial_provided',
        ),
        migrations.RemoveField(
            model_name='person',
            name='DOB',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE '), ('OTHERS ', 'OTHERS ')], max_length=25, null=True),
        ),
    ]
