# Generated by Django 3.2.15 on 2022-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0022_auto_20220828_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='DOB',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=True, max_length=2),
        ),
    ]
