# Generated by Django 3.2.15 on 2022-08-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0024_auto_20220828_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='DOB',
        ),
    ]
