# Generated by Django 3.2.15 on 2022-08-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0025_remove_person_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='DOB',
            field=models.DateField(null=True, verbose_name='DOB(dd/mm/yy)'),
        ),
    ]
