# Generated by Django 3.2.15 on 2022-08-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0026_person_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='Account_Holder',
        ),
    ]
