# Generated by Django 3.2.15 on 2022-08-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personapp', '0027_rename_name_person_account_holder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Account_Holder',
            new_name='name',
        ),
    ]
